name: churn-env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit==1.32.0
    - tensorflow==2.15.0
    - protobuf==3.20.3
    - pandas
    - numpy
    - scikit-learn
    - joblib